name: meditro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.0
  intl: ^0.17.0
  url_launcher: ^6.1.0 
  path_provider: ^2.1.5
  flutter_file_downloader: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # ✅ أضف هذا السطر
  open_file: ^3.5.9
  google_fonts: 4.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
